---
- name: "Install Required Taps"
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_taps }}"

- name: Install Homebrew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ homebrew_packages }}"

- name: Install Homebrew Casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: "{{ allow_external_apps }}"
  loop: "{{ homebrew_casks }}" 
