dockitems_remove:
  - Siri
  - Contacts
  - Notes
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iBooks
  - News
  - Podcasts
  - TV

dockitems_persist:
  - name: Safari
    path: "/Applications/Safari.app"
    pos: 1
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: Mail
    path: "/System/Applications/Mail.app"
    pos: 3
  - name: Calendar
    path: "/System/Applications/Calendar.app"
    pos: 4
  - name: Reminders
    path: "/System/Applications/Reminders.app"
    pos: 5
  - name: WhatsApp
    path: "/Applications/WhatsApp.app"
    pos: 6
  - name: Microsoft Teams
    path: "/Applications/Microsoft Teams.app"
    pos: 7
  - name: Visual Studio Code
    path: "/Applications/Visual Studio Code.app"
    pos: 8
  - name: Notion
    path: "/Applications/Notion.app"
    pos: 9
  - name: Terminal
    path: "/System/Applications/Utilities/Terminal.app"
    pos: 10