---
mac_app_store_ids:
  - { id: 441258766,  name: "Magnet" }
  - { id: 1284863847, name: "Unsplash WallPapers"}
  - { id: 937984704,  name: "Amphetamine"}
  - { id: 1482920575, name: "DuckDuckGo Privacy Essentials" }
  - { id: 1352778147, name: "Bitwarden" }