---
vscode_extensions:
  - CoenraadS.bracket-pair-colorizer-2
  - hashicorp.terraform
  - marcostazi.VS-code-vagrantfile
  - ms-azuretools.vscode-docker
  - ms-vscode-remote.remote-containers
  - ms-vscode.atom-keybindings
  - ritwickdey.LiveServer
  - ms-vscode.powershell
  - ms-python.python
  - tomaciazek.ansible
  - docsmsft.docs-preview
  - ms-mssql.mssql
  - janisdd.vscode-edit-csv